### ISSUE TITLE
Not worked with jsonb column in Rails 4.2.4, Thanks.

### ISSUE THREAD

**Issue by zw963** [timsly/carrierwave-serializable#16]
```ruby
# schema.rb
    t.jsonb    "delivery_info",         default: {}
```

```ruby
  # order.rb

  # add return_logistics_image accessor method.
  store_accessor :delivery_info, :return_logistics_image
  mount_uploader :return_logistics_image, ImageUploader, serialize_to: :delivery_info
```
When create a new order object, exist following error:
```
NoMethodError (undefined method `return_logistics_image_changed?' for #<Order:0x007f1af7c68338>):
  app/models/order_transition.rb:7:in `block in <class:OrderTransition>'
  app/models/order.rb:182:in `transition_to!'
  app/models/order/buyer_action.rb:10:in `accept'
  app/models/concerns/set_order_action_callback.rb:13:in `public_send'
  app/models/concerns/set_order_action_callback.rb:13:in `block (2 levels) in method_added'
  app/models/concerns/set_order_action_callback.rb:12:in `block in method_added'
  app/api/api/buyer_action.rb:26:in `accept'
  app/controllers/orders_controller.rb:33:in `action!'
  app/controllers/buyer_orders_controller.rb:131:in `action!'
```

**Comment by zw963** [comment]
Sorry, NoMethodError (undefined method `return_logistics_image_changed?'  is fixed when restart server, But,  ``order.return_logistics_image = params[:return_logistics_image]`` is not worked in controller.

**Comment by zw963** [comment]
Can worked with jsonb, sorry!
